### ISSUE TITLE
Abolish usage of NUC files

### ISSUE THREAD

**Issue by orinuse** [orinuse/L4D2_default_map_addons#1]
All projects that use NUC files have them located under the "packing" folder while the NUT versions in the "src" folder.

To abolish NUC files is to move in the NUT files then remove the NUC files, along with any tool that allows creating more NUCs. (`L4D2VScriptEditor`)

**Comment by Shadowysn** [comment]
Seems simple enough. I should get rid of the appropriate "scripts" folder in "src", right?

**Comment by orinuse** [comment]
> Seems simple enough. I should get rid of the appropriate "scripts" folder in "src", right?

Correct, the issue is good to be closed afterwards

**Comment by Shadowysn** [comment]
Should be done. Let me know if there's any more issues.
