### ISSUE TITLE
weapon_spawn ents do not get handled by the director

### ISSUE THREAD

**Issue by Shadowysn** [orinuse/L4D2_default_map_addons#11]
Teleporting to each **_spawn** entity _(making sure the saferoom door opens everytime to load the script)_ and restarting at least 5 times for each entity, the `weapon_item_spawn`, `upgrade_spawn`, and single `weapon_pistol_spawn` entities didn't appear to have any issues with the director randomizing and spawning them properly.
However, the `weapon_spawn` entities that weren't tied to `point_script_template` entities never seemed to spawn anything, and they glitch the pick-up hand animation as if there is a weapon there.
```
orin_weapons_patch
orin_weapons_patch2
orin_weapons_patch4
orin_weapons_patch13
orin_weapons_patch16
```
The holdout `weapon_spawn`s properly spawned from the `point_script_template`s that were given their `ForceSpawn` inputs from the random case, and thanks to the template entity they won't glitch the pick-up hand anim.

**Comment by orinuse** [comment]
Huh, good eye. From the sounds of this, I'll have to rid all `weapon_spawn` entites that aren't forced to always spawn and then substitute for random entity classnames.

Will look into this further, so sleep on this for the moment.

**Comment by orinuse** [comment]
@Shadowysn I've made a commit in response to your issue, could you review my changes for anything off?

**Comment by orinuse** [comment]
[Commit](https://github.com/orinuse/L4D2_default_map_addons/commit/2c86c418bc63738a59708eccff9b47e39ddb8597) was updated.
