### ISSUE TITLE
Disambiguate and document the DirectorOptions keys in the "blaring alarm" script

### ISSUE THREAD

**Issue by orinuse** [orinuse/L4D2_default_map_addons#3]
At [#L11-L13](https://github.com/orinuse/L4D2_default_map_addons/blob/main/coop/MP-DeadAirTerminals/packing/scripts/vscripts/c11m4_patch_alarm_blaring.nut#L11-L13)  inside the "blaring alarm" script, despite its comments, are ambiguous and is unknown if they provide any meaningful functionality:

```nut
	// One of these when true, disables the Mob spawn cues I think
	LockTempo = true	// This works as the VDC describes
	PanicForever = true	// test this more
```

Which of these keys function as the comment describes? What does "as the VDC describes" mean? Do either of them provide any undocumented benefits?

**Comment by Shadowysn** [comment]
I remember playing with a console command more than once called **director_panic_forever** that might be the same thing as **DirectorOptions.PanicForever**
When I started a normal panic event through **director_force_panic_event**, the mob cues still played as the panic event continued being played forever.
I'll need to go in game tomorrow to test **LockTempo** and **PanicForever** fully, though

**Comment by Shadowysn** [comment]
Either of the values don't seem to control the Mob spawn cues, they don't play even if both of these are false.
The entitygroups are properly spawned and working through IncludeScript unlike Blood Harvest Survival map 4.
After starting the metal detector it still stays on BUILD_UP even without **LockTempo**. Might be something with the scripted event.
Honestly unsure on how the values are implemented, the way the **DirectorOptions** are setup I can't print the values that're added from the scripts through **script g_ModeScript.DeepPrintTable(g_MapScript.DirectorOptions)** and that makes me also unsure if the values can actually work through that.
I also can't find major differences between having both values off, on, and then one of them false and one of them true.

**Comment by orinuse** [comment]
> Honestly unsure on how the values are implemented, the way the **DirectorOptions** are setup I can't print the values that're added from the scripts through **script g_ModeScript.DeepPrintTable(g_MapScript.DirectorOptions)** and that makes me also unsure if the values can actually work through that.

Scripts loaded through the Director's `BeginScript` input may be placed in the `LocalScript` scope; try `DeepPrintTable(g_MapScript.LocalScript.DirectorOptions)` instead.

> Either of the values don't seem to control the Mob spawn cues, they don't play even if both of these are false.
> After starting the metal detector it still stays on BUILD_UP even without **LockTempo**. Might be something with the scripted event.
> I also can't find major differences between having both values off, on, and then one of them false and one of them true.

Since both of them don't affect mob spawning cues or any other related element of the script's structured "mini-finale", it should be wise to remove the 3 lines then close the issue.

For `LockTempo` and `PanicForever`, it could be that they apply to different scenarios, like when there's no events active, but that's outside our concerns for now. (Unless you'd like the VDC updated, which'd be fine by me)

**Comment by Shadowysn** [comment]
> Scripts loaded through the Director's `BeginScript` input may be placed in the `LocalScript` scope; try `DeepPrintTable(g_MapScript.LocalScript.DirectorOptions)` instead.

It just seems to print the same values as `DeepPrintTable(g_MapScript.DirectorOptions)`
I give up trying to print those values using console, it's proving to be more hassle than it's worth.

I've removed the lines in the [53446df](https://github.com/orinuse/L4D2_default_map_addons/commit/53446dfb529b5a0da21bc2427c04ae244a505161) commit now.
