### ISSUE TITLE
Standardise `while` loops that iterate through `Entities`

### ISSUE THREAD

**Issue by orinuse** [orinuse/L4D2_default_map_addons#5]
For example, I'll take the loop at [#L33-L39](https://github.com/orinuse/L4D2_default_map_addons/blob/main/coop/MP-DeadAirTerminals/packing/scripts/vscripts/c11m4_patch_alarm_blaring.nut#L33-L39) of the "Blaring Alarm" script:
```nut
local spawn_zombie_alarm2 = null
while( spawn_zombie_alarm2 = Entities.FindByName(spawn_zombie_alarm2, "spawn_zombie_alarm2") )
{
//	EntFire("!self", "AddOutput", "OnSpawnNormal !self:RunScriptCode:RushVictim(null, 8000):0.1:-1", 0, spawn_zombie_alarm2)
	EntityOutputs.AddOutput(spawn_zombie_alarm2, "OnSpawnNormal", "!self", "RunScriptCode", "RushVictim(null, 8000)", 0.1, -1)
	EntFire("!self", "SpawnZombie", null, (RandomFloat(0.1, 0.3)), spawn_zombie_alarm2)
}
```

What's intended to be done is:
```nut
for ( local ent=null; ent = Entities.FindByName( ent, "spawn_zombie_alarm2" );; )
{
	EntityOutputs.AddOutput( ent, "OnSpawnNormal", "!self", "RunScriptCode", "RushVictim(null, 8000)", 0.1, -1 )
	EntFire( "!self", "SpawnZombie", null, RandomFloat(0.1, 0.3), ent )
}
```

The above code is untested so I cannot guarantee its devoid of errors, but I'd really appreciate any help.

**Comment by Shadowysn** [comment]
The second semicolon near the end of the **for ()** line errors out, but once that's removed it works.
Replaced the other while loops in **c11m4_patch_master.nut** and **c11m4_missingweapons_group.nut** as well.

**Comment by orinuse** [comment]
Reopening as I'd like the names of the initialised loop control variable standardised to `ent` aswell, apologies for not clarifying that detail.

> The second semicolon near the end of the **for ()** line errors out, but once that's removed it works.

Whoops, there should only be 2 semicolons within the brackets of a `for` loop and not 3.

**Comment by Shadowysn** [comment]
[Oops, forgot to inform about the recent commit done.](https://github.com/orinuse/L4D2_default_map_addons/commit/889c4cf6ae8ed2f135212d3435a68ab3b2351e28) Is this fixed now?

**Comment by orinuse** [comment]
> [Oops, forgot to inform about the recent commit done.](https://github.com/orinuse/L4D2_default_map_addons/commit/889c4cf6ae8ed2f135212d3435a68ab3b2351e28) Is this fixed now?

The variables at the end of the file is better left alone, otherwise all is just right! Closing issue.
