### ISSUE TITLE
Refinement chores of "master" script to clear

### ISSUE THREAD

**Issue by orinuse** [orinuse/L4D2_default_map_addons#7]
Rather straightforward chores:
1. Cut down on comments by removing ones that either are separators which contains `=` or make meaningful comments concise. (This includes the `SetContext` method at the bottom)
2. Make all one-line `if` statements use Allman-styled brackets.
3. Move `ValidateScriptScope()` out if-statements then remove said statements and replace the opening bracket with a newline space.
4. The following code should be condensed into a `foreach()`:
```nut
EntFire("van_push1_trigger", "Kill")
EntFire("van_push2_trigger", "Kill")
EntFire("van_push3_trigger", "Kill")
EntFire("van_push4_trigger", "Kill")
EntFire("van_push5_trigger", "Kill")
EntFire("van_push6_trigger", "Kill")

local van_start_relay = Ent("van_start_relay")
EntityOutputs.RemoveOutput(van_start_relay, "OnTrigger", "van_push1_trigger", "Enable", "")
EntityOutputs.RemoveOutput(van_start_relay, "OnTrigger", "van_push2_trigger", "Enable", "")
EntityOutputs.RemoveOutput(van_start_relay, "OnTrigger", "van_push3_trigger", "Enable", "")
EntityOutputs.RemoveOutput(van_start_relay, "OnTrigger", "van_push4_trigger", "Enable", "")
EntityOutputs.RemoveOutput(van_start_relay, "OnTrigger", "van_push5_trigger", "Enable", "")
EntityOutputs.RemoveOutput(van_start_relay, "OnTrigger", "van_push6_trigger", "Enable", "")
```

**Comment by Shadowysn** [comment]
3 and 4 are done, but 1 and 2 might need oversight and judgement.

**Comment by orinuse** [comment]
Sure, what's left will be finalised by me. Appreciate the commit.

**Comment by orinuse** [comment]
Closing if there aren't any more technical issues.

**Comment by Shadowysn** [comment]
There was an error with removing the **triggerName** variable and not changing the **RemoveOutput** but other than that, the script seems to work fine except for **Context** getting/setting.

The _world_ part of _worldSaidSafeSpotAhead_ is unneeded and makes it useless when setting context on **worldspawn**. The talker system seems to automatically append _world_ behind all **worldspawn** context when checking for them.

**GetContext** returns **null** for only-numbers set through anything, so it's a _GetContext-related_ problem. So checking **SaidSafeSpotAhead** through **GetContext** is useless.
I thought **SetContext** only works properly with strings of text and not strings of numbers, but from further testing it still seems to work.
Regardless I've replaced **SetContext** with **SetContextNum** and a number type for it's 2nd argument.

**Comment by orinuse** [comment]
Wonderful, thank you @Shadowysn for fixing my errors and the context knowledge! Especially the bit about the "world" prefix.

I noticed the condition for **SetContext** has been removed but I suppose that isn't a problem? Other than that, this issue is good to close if no other technical problems are present and all function as intended, especially the concept blocking.

**Comment by Shadowysn** [comment]
Alright. Sorry for the various minor commits, I undid the worldspawn variable removal commit referenced on this issue and updated the GetContext comment to remove the SetContext bit.
