### ISSUE TITLE
developer() Error Expression Expected for weaponsgroup script

### ISSUE THREAD

**Issue by Shadowysn** [orinuse/L4D2_default_map_addons#8]
The **developer()** prints of both [L14](https://github.com/orinuse/L4D2_default_map_addons/blob/e7f54c073d8e9540fcf09ee997b77abdb5c02170/coop/MP-DeadAirTerminals/packing/scripts/vscripts/entitygroups/patch_da_weaponsgroup.nut#L14) and [L26](https://github.com/orinuse/L4D2_default_map_addons/blob/e7f54c073d8e9540fcf09ee997b77abdb5c02170/coop/MP-DeadAirTerminals/packing/scripts/vscripts/entitygroups/patch_da_weaponsgroup.nut#L26) are missing a closing bracket for their ends.
```
VSCRIPT [Orin]: Running 'c11m4_reserved_wanderers' ADDON
Hey! no entity for info_scriptRanOnce
****************************
**      DLC Patch
** Dead Air (Terminals)
****************************
scripts/vscripts/entitygroups/patch_da_weaponsgroup.nut line = (17) column = (3) : error expression expected
FAILED to compile and execute script file named entitygroups/patch_da_weaponsgroup

AN ERROR HAS OCCURED [Failed to include script "entitygroups/patch_da_weaponsgroup"]

CALLSTACK
*FUNCTION [IncludeScript()] unnamed line [75]
*FUNCTION [main()] scripts/vscripts/c11m4_reserved_wanderers.nut line [29]

LOCALS
[scope] TABLE
[name] "entitygroups/patch_da_weaponsgroup"
[this] TABLE
[vargv] ARRAY
[this] TABLE
Error running script named c11m4_reserved_wanderers
```
I've tried to fix this, but it just seems to run into another separate error I'm confused on.
The **format()** functions seem to be the culprit, but I can't find why:
```
AN ERROR HAS OCCURED [string expected for the specified format]

CALLSTACK
*FUNCTION [DeleteUnwantedWeapon()] scripts/vscripts/entitygroups/patch_da_weaponsgroup.nut line [14]
*FUNCTION [unknown()] scripts/vscripts/entitygroups/patch_da_weaponsgroup.nut line [520]
*FUNCTION [SpawnEntityGroup()] scripts/vscripts/sm_spawn.nuc line [733]
*FUNCTION [SpawnSingle()] scripts/vscripts/sm_spawn.nuc line [1022]
*FUNCTION [main()] scripts/vscripts/c11m4_reserved_wanderers.nut line [29]

LOCALS
[ent] INSTANCE
[origin] INSTANCE
[classname] "weapon_spawn"
[this] TABLE
[DeleteUnwantedWeapon] CLOSURE
[rarity] 0
[entity] INSTANCE
[this] TABLE
[spawnedEntity] INSTANCE
[spawnEnt] TABLE
[@INDEX@] "orin_weapons_patch16"
[spawnedNameList] ARRAY
[bSuccess] false
[groupSpawnTables] TABLE
[tableidx] 22
[groupInst] TABLE
[angles] NULL
[origin] NULL
[positionEnt] NULL
[group] TABLE
[this] TABLE
[ang] NULL
[pos] NULL
[entityAt] NULL
[entityGroup] TABLE
[this] TABLE
[vargv] ARRAY
[this] TABLE
```

**Comment by orinuse** [comment]
Yikes, closed wrong commit, I meant to close #8.

@Shadowysn could you do a test on the commit's changes and see if all works fine?

**Comment by Shadowysn** [comment]
> Yikes, closed wrong commit, I meant to close #8.
> 
> @Shadowysn could you do a test on the commit's changes and see if all works fine?

Nope, still the same **string expected for the specified format** error on the same **format()** lines.
I'd get rid of the **format()** function and use snake-case *(I presume it's named, idk)* which works with printing the entity and Vector.
`print( ent+" - "+ent.GetOrigin()+"\n" )`
Result:
```
([971] weapon_spawn) - (vector : (82.875000, 5163.968750, 337.000000)
([686] prop_physics) - (vector : (152.250000, 5171.187500, 306.875000)
([318] weapon_pistol_magnum_spawn) - (vector : (302.000000, 5572.000000, 298.062500)
([972] weapon_spawn) - (vector : (43.062500, 5169.968750, 337.000000)
([687] prop_physics) - (vector : (109.343750, 5208.375000, 299.500000)
```

**Comment by orinuse** [comment]
> I'd get rid of the **format()** function and use snake-case *(I presume it's named, idk)* which works with printing the entity and Vector.
> `print( ent+" - "+ent.GetOrigin()+"\n" )`

I'm good with that, guess sometimes a simple boring method proves to be better long-term.

About your unsureness, **snake_case** is a naming convention where identifiers separate words with an underscore rather than a whitespace. E.g. "mynumber" vs camelCase "myNumber" vs snake_case "my_number".

Issue is good to be closed if no further actions are to be taken, however do that after you removed the comments you added.

**Comment by Shadowysn** [comment]
The only thing I can call it is **plus-case** then, but oh well. ¯\\\_(ツ)\_/¯
