### ISSUE TITLE
In "alarm2" script, tie up the comments's loose ends

### ISSUE THREAD

**Issue by orinuse** [orinuse/L4D2_default_map_addons#9]
Two things:
1. In the `DirectorOptions` table, these comments are present:
```nut
//        I don't think this belongs here, but with that StageInfo_Execute() function 
 /*        SpawnSetPosition = Vector(2700.272217, 3429.643555, 152.031250) 
         SpawnSetRadius = 800 
         SpawnSetRule = SPAWN_POSITIONAL 
  
         PreferredMobDirection = SPAWN_POSITIONAL */
```

The code within these comments have errors and possibly the reason for being commented out. Please replace the comments with the following code and test if this makes mobs spawn around the given Vector:
```nut
        PreferredMobPosition = Vector(2700.272, 3429.644, 152.031) 
        PreferredMobPositionRadius = 800
        PreferredMobDirection = SPAWN_NEAR_POSITION
```

2. There's a commented-out `EntFire()` call that seems to accomplish the same purpose to the `EntityOutputs.AddOutput()` call below it, so remove the comment.

This should be the final issue before this VPK is good for a github release of some sort. Anyways, thank you and have a good day.

**Comment by Shadowysn** [comment]
Tested 3 times each with both your intended vector and a vector of opposite direction. I used the bombed hole as a midway point between the two vectors and saw that **PreferredMobPosition** definitely influenced the mobs to spawn around the chosen vector.

As for **PreferredMobPositionRadius**, at first I thought it might be the range which a survivor has to be in for the position to take effect.
But then stray packs of commons spawned in locations not lining up with the vector's direction both in-range (sometimes) and out-of-range, and when set to a very high value the mobs spawn anywhere again.
So a range of navmeshes to spawn in, a failsafe for if the survivor's out-of-range, or varied stray packs just to make sure it's not a predictable location?
_(I made sure to remove the **info\_zombie\_spawns** during testing as well)_

I'm inconclusive on what **PreferredMobPositionRadius** exactly does.

**Comment by orinuse** [comment]
@Shadowysn Terribly sorry for this, I've given you a *non-existant* DirectorOptions key!

According to the example `dash` mutation, **PreferredMobDirectionRadius** does not exist and instead it should be **PreferredMobPositionRange**!

Sorry for the inconvenience.

**Comment by Shadowysn** [comment]
ouuwh 😵

**Comment by Shadowysn** [comment]
My guess now is the **PreferredMobPositionRange** setting is the range of nav-mesh spots to spawn in, which may also act as a _"radius"_ for survivors where it falls back on normal spawning when all the preferred spots are too far away.
Still doesn't explain the stray commons that spawn anywhere else than the main pack that obey the range, but it could be some tolerance or randomness.

**Comment by Shadowysn** [comment]
Looks like my guess may be correct. This happens when I'm too far away from the preferred mob position and it's range. _(ConVar **z_debug_mob_spawn 1**)_
```
VSCRIPT [Orin]: Running 'patch_da_alarm2' 
(MOB) 1114.07: MOB SPAWN ERROR: Empty spawn area set, switching to ANYWHERE
ChooseMobSpawnAreas: m_mobSpawnAreas[0].pArea 2642 has 84 population
ChooseMobSpawnAreas: m_mobSpawnAreas[1].pArea 722 has 256 population
Mob zombie spawned in spawn area 0 - 83 left
Mob zombie spawned in spawn area 1 - 255 left
Mob zombie spawned in spawn area 0 - 82 left
Mob zombie spawned in spawn area 1 - 254 left
Mob zombie spawned in spawn area 0 - 81 left
Mob zombie spawned in spawn area 1 - 253 left
Mob zombie spawned in spawn area 0 - 80 left
(MOB) 1114.33: MOB SPAWN ERROR: Empty spawn area set, switching to ANYWHERE
ChooseMobSpawnAreas: m_mobSpawnAreas[0].pArea 1373 has 576 population
ChooseMobSpawnAreas: m_mobSpawnAreas[1].pArea 340 has 576 population
Mob zombie spawned in spawn area 1 - 575 left
Mob zombie spawned in spawn area 0 - 575 left
Mob zombie spawned in spawn area 1 - 574 left
Mob zombie spawned in spawn area 0 - 574 left
Mob zombie spawned in spawn area 1 - 573 left
Mob zombie spawned in spawn area 0 - 573 left
Mob zombie spawned in spawn area 1 - 572 left
Mob zombie spawned in spawn area 1 - 571 left
Mob zombie spawned in spawn area 1 - 570 left
ChooseMobSpawnAreas: m_mobSpawnAreas[0].pArea 2726 has 48 population
ChooseMobSpawnAreas: m_mobSpawnAreas[1].pArea 1693 has 60 population
Mob zombie spawned in spawn area 0 - 47 left
Mob zombie spawned in spawn area 1 - 59 left
Mob zombie spawned in spawn area 0 - 46 left
Mob zombie spawned in spawn area 1 - 58 left
```
In that case, the position may need to be moved closer.

**Comment by orinuse** [comment]
> Looks like my guess may be correct. This happens when I'm too far away from the preferred mob position and it's range. _(ConVar **z_debug_mob_spawn 1**)_
> In that case, the position may need to be moved closer.

The choices may be delicate so lets step back first and try to understand the meaning of these chosen numbers.. beyond what point do the mobs not switch to ANYWHERE?

I believe one of the intents behind these positional mob spawnings may be to force commons be spawned at an area that will make them engage face-to-face with rushers, but we'll see.


I'd be up to be doing a live analysing session of l4d2 in Discord, if you'd like to

**Comment by Shadowysn** [comment]
Thanks for clarifying, the moving-it-further was an offhand guessed suggestion that I was going to retract anyway, though it may be possible to dynamically change the position somehow, if the **DirectorOptions** table acts like I think it could.
I've found that being a little further away from the hole, being nearer to the metal detector, was the max I could go until the mobs switched to **ANYWHERE**.

Also, the [L29](https://github.com/orinuse/L4D2_default_map_addons/blob/main/coop/MP-DeadAirTerminals/packing/scripts/vscripts/patch_da_alarm2.nut#L29) **SpawnZombie EntFire** doesn't work because you're targeting **!self** when **EntFire** doesn't provide a **caller** variable.
Switching it to **DoEntFire**, adding in the caller to pass it to, and swapping the **null**'d 3rd argument with empty string "" to prevent the crash works.

**Comment by orinuse** [comment]
> I've found that being a little further away from the hole, being nearer to the metal detector, was the max I could go until the mobs switched to **ANYWHERE**.

I am not clear on what "a little further away" from the crater or "being nearer" to the metal detector means, sorry but you'd have to provide more details or use images. (further back or further front from what perspective? near in what manner?)

> Switching it to **DoEntFire**, adding in the caller to pass it to, and swapping the **null**'d 3rd argument with empty string "" to prevent the crash works.

Good catch, but for standardising my scripts, I'd go with **EntFire()** with the first argument as **!activator**.

**Comment by Shadowysn** [comment]
> I am not clear on what "a little further away" from the crater or "being nearer" to the metal detector means, sorry but you'd have to provide more details or use images. (further back or further front from what perspective? near in what manner?)

Ah sorry, I was thinking in a line between the metal detector and the crater.
The spot is somewhere in the highlighted nav area.
![c11m4_terminal0002](https://user-images.githubusercontent.com/44493487/212532248-c85c5d6d-d88d-49a8-8da8-b86d75acbf97.png)

**Comment by orinuse** [comment]
The feature still has loose ends but all ones that are script-sided are tied up, with the rest being on the nav-side.

No further edits are required for the script, so I'm closing this.
